application: blogek-3v
version: 1-1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico

- url: /robots\.txt
  static_files: robots.txt
  upload: robots\.txt

- url: /static/(.*)
  static_files: static/\1
  upload: static/(.*)

- url: /links/new_link
  script: main.app
  login: admin

- url: /blog/new_post
  script: main.app
  login: admin

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.1"

